name: IntPic
version: "0.4.0"
license: "GPL-2.0-or-later"
date: 2024-08-30
description: |
    A package for drawing integers

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/

GAP: "4.7"

needed-pkgs:
    - name: "numericalsgps"
      version: "1.0"
      url: "https://gap-packages.github.io/numericalsgps"
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/intpic
readme: README.md
packageinfo: https://gap-packages.github.io/intpic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/intpic/releases/download/v0.4.0/IntPic-0.4.0.tar.gz

abstract: |
    The <span class="pkgname">IntPic</span> package, is a package for drawing integers, by emphasizing some subsets.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    emphasize, highlight, draw, integer, picture.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Del24</span>]   <b class='BibAuthor'>Delgado, M.</b>,
     <i class='BibTitle'>IntPic, A package for drawing integers,
             Version 0.4.0</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/intpic">https://gap-packages.github.io/intpic</a></span>.
    </p>
    

bibtex: |
    @misc{ IntPic,
      author =           {Delgado, M.},
      title =            {{IntPic},  A  package  for drawing integers, {V}ersion
                          0.4.0},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/intpic}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{intpic}}},
      keywords =         {emphasize; highlight; draw; integer; picture},
      printedkey =       {Del24}
    }

