name: IntPic
version: 0.3.0
date: 2022-06-02
description: |
    A package for drawing integers

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/

GAP: "4.7"

needed-pkgs:
    - name: "numericalsgps"
      version: "1.0"
      url: "https://gap-packages.github.io/numericalsgps"
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/intpic
readme: README.md
packageinfo: https://gap-packages.github.io/intpic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/intpic/releases/download/v0.3.0/IntPic-0.3.0.tar.gz

abstract: |
    The <span class="pkgname">IntPic</span> package, is a package for drawing integers, by emphasizing some subsets.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
